<?php

namespace AppBundle\Repository;

/**
 * GifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GifRepository extends \Doctrine\ORM\EntityRepository
{
}
