# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    my_app.discount_manager:
        class: AppBundle\Manager\DiscountManager

    my_app.discount.validity_checker:
        class: AppBundle\Service\Checker\ValidityChecker
        tags:
            - {name: discount_checker}
            
    my_app.discount.currency_checker:
        class: AppBundle\Service\Checker\CurrencyChecker
        tags:
            - {name: discount_checker}

    my_app.form.type.post:
        class: AppBundle\Form\Type\PostType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    my_app.image_type_extension:
        class: AppBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    my_app.gif_manager:
        class: AppBundle\Manager\GifManager
        arguments:
            - '@giphy_client'
            - '@doctrine.orm.entity_manager'

    giphy_client:
        class: rfreebern\Giphy